FROM node:16.14.2-alpine
# WORKDIR /app/myapp
# WORKDIR /
# WORKDIR /korukoru
# WORKDIR /aploapolo
# WORKDIR koko
# VOLUME [ "/kokodesuyo" ]

# VOLUME /fe
# VOLUME /be


# VOLUME /fe/next
# VOLUME /be/java
# CMD [ "yarn", "build" ]

